### ISSUE TITLE
How to quantize to int8？

### ISSUE THREAD

**Issue by ZTMIDGO** [harrisonvanderbyl/rwkv-onnx#3]
Is the code able to quantize the model to int8?

**Comment by harrisonvanderbyl** [comment]
this code does not, but I know that it is definitely possible.
This will be looked into.

**Comment by ZTMIDGO** [comment]
> this code does not, but I know that it is definitely possible. This will be looked into.

I run 430m rwkv-v4 on Android, but when I try to use the quantized fp16 1B5 model, it fails because it exceeds the 2GB size limit, so I want to seek a quantized uint8 model.

the project: https://github.com/ZTMIDGO/RWKV-Android

**Comment by harrisonvanderbyl** [comment]
Huh, with external bin file, you can bypass the 2GB limit, ill see if I can get it working with external data
