### ISSUE TITLE
The model is running abnormally

### ISSUE THREAD

**Issue by ZTMIDGO** [harrisonvanderbyl/rwkv-onnx#4]
I use convert.py to convert the rwkv model: https://huggingface.co/BlinkDL/rwkv-4-world/blob/main/RWKV-4-World-0.1B-v1-20230520-ctx4096.pth

Convert to onnx model (FP32), run the model, the output data is NaN, the output name is name: matvec_1122_out

**Comment by harrisonvanderbyl** [comment]
You will need a different tokenizer for the world models

**Comment by harrisonvanderbyl** [comment]
I was able to get fp16 1B5 raven model working with Android

**Comment by ZTMIDGO** [comment]
> I was able to get fp16 1B5 raven model working with Android

Can you upload the onnx model to huggungface, my computer configuration is too low, there is no way to convert the 1B5 model.
